version: '3.8'

services:
    builder:
        container_name: builder
        image: golang:latest
        volumes:
            - ./:/source
            - build-volume:/usr/src/app
        environment:
            - GO111MODULE=on
            - CGO_ENABLED=0
            - GOOS=linux

        command: go mod download && go build -a -installsuffix cgo -o /usr/src/app/main /source/main.go

    server:
        container_name: server
        image: alpine:latest
        volumes:
            - build-volume:/usr/src/app
        ports:
            - "9090:9090"
        links:
            - builder
        command: /usr/src/app/main
    
    envoy:
        container_name: envoy
        image: envoyproxy/envoy:v1.14-latest
        volumes:
            - ./envoy:/etc/envoy
        ports:
            - "8080:8080"
            - "9901:9901"
            
        command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    
volumes:
    build-volume:

# docker-compose -f docker/docker-compose.yaml up