version: '3'
services:
    builder:
        build:
            context: .
            target: golang:latest
        volumes:
            - ./build:./
        working_dir: /app
        environment:
            MAINTAINER: "Hector Morales <hector.morales.carnice@gmail.com>"
        links:
            - server

    server:
        build:
            context: .
            target: alpine:latest
        volumes:
            - .:/app
        ports:
            - "9090:9090"
        working_dir: /app
volumes:
    logvolume01: {}
        